/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer;

/**
 *
 * @author joaoh
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
    initComponents();
    initEventos(); // adicione essa linha
}

private void initEventos() {
    menuCadPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            controller.GerInterGrafica.getInstancia().abrirCadCliente();
        }
    });

    menuEditPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            controller.GerInterGrafica.getInstancia().abrirEditarPaciente();
        }
    });

    menuListPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            controller.GerInterGrafica.getInstancia().abrirListarPaciente();
        }
    });

    menuAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            controller.GerInterGrafica.getInstancia().abrirAgenda();
        }
    });

    menuProntuario.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            controller.GerInterGrafica.getInstancia().abrirProntuario();
        }
    });

    menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            System.exit(0);
        }
    });
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuPaciente = new javax.swing.JMenu();
        menuCadPaciente = new javax.swing.JMenu();
        menuEditPaciente = new javax.swing.JMenu();
        menuListPaciente = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenu();
        menuAgenda = new javax.swing.JMenu();
        menuProntuario = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPaciente.setText("Paciente");

        menuCadPaciente.setText("Cadastrar Paciente");
        menuPaciente.add(menuCadPaciente);

        menuEditPaciente.setText("Editar Paciente");
        menuPaciente.add(menuEditPaciente);

        menuListPaciente.setText("Listar Paciente");
        menuPaciente.add(menuListPaciente);
        menuPaciente.add(jSeparator1);

        menuSair.setText("Sair");
        menuPaciente.add(menuSair);

        jMenuBar1.add(menuPaciente);

        menuAgenda.setText("Agenda");
        jMenuBar1.add(menuAgenda);

        menuProntuario.setText("Prontuário");
        jMenuBar1.add(menuProntuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuCadPaciente;
    private javax.swing.JMenu menuEditPaciente;
    private javax.swing.JMenu menuListPaciente;
    private javax.swing.JMenu menuPaciente;
    private javax.swing.JMenu menuProntuario;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
